<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Framework.Infrastructure</RootNamespace>
    <AssemblyName>Framework.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.AI.Core\BuildingBlocks.AI.Core.csproj" />
    <ProjectReference Include="..\BuildingBlocks.AI.Azure\BuildingBlocks.AI.Azure.csproj" />
    <ProjectReference Include="..\BuildingBlocks.AI.Local\BuildingBlocks.AI.Local.csproj" />
    <ProjectReference Include="..\Framework.Application\Framework.Application.csproj" />
    <ProjectReference Include="..\Framework.Domain\Framework.Domain.csproj" />
  </ItemGroup>

</Project>

